//
// Created by andrzej on 16.06.19.
//

#ifndef BRAM_CONTROLLER_WRITE_COMMAND_VERBOSE_HPP
#define BRAM_CONTROLLER_WRITE_COMMAND_VERBOSE_HPP


class WriteCommandVerbose {

};


#endif //BRAM_CONTROLLER_WRITE_COMMAND_VERBOSE_HPP
